import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';
import thumbnail from '../public/thumbnail.png';

function scrollIntoView(id){  
  let element = document.getElementById(id);

  element.scrollIntoView(true);
}

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/3a5e0f4177.js" crossOrigin="anonymous"></script>
      </Head> */}

      <main className={styles.main}>
        <br></br>
        <h1 className={styles.title}>
          Who's Here? <a role="button" onClick={() => scrollIntoView('description')}>Kilroy is here!</a>
        </h1>
        <br></br>
        <br></br>
        <Image src={thumbnail} alt="Kilroy" className={styles.image} width="1013" height="582"/>
        <div className={styles.description} id="description">
          <h1> <a> About Kilroy </a></h1>
          <br></br>
          <div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada fringilla dapibus. Fusce purus diam, vestibulum non dui sit amet, sollicitudin ultricies dolor. Mauris tempus, odio finibus placerat porttitor, leo arcu tristique mi, id dictum lacus lorem sit amet metus. Aliquam vel felis nulla. Aliquam erat volutpat. Phasellus accumsan accumsan mi, sed vehicula quam fermentum pretium. Mauris ex metus, placerat ac consequat non, venenatis condimentum odio. Vivamus semper odio ut dictum consequat. Phasellus ullamcorper, nulla in semper suscipit, ligula mauris tempor augue, eget dignissim quam enim non quam. Pellentesque at vulputate mi. Nulla pellentesque massa eget ipsum commodo, ut aliquam justo accumsan. Suspendisse potenti. Maecenas in sagittis nunc, nec dictum enim. Nam ante felis, ultricies ac magna quis, dictum scelerisque purus.</p>
          </div>
        </div>
      </main>
    </div>
  )
}
